#!/bin/bash
# gen_objs_doob.sh [V1 [V2]]
#
# Run puffup_c against every prime CLERS at vertex counts V1..V2 (default
# 4..50), storing each emitted OBJ under its CLERS-named filename in
# $OUTDIR/v{V}/{CLERS}.obj. OBJs persist after the run; rerun with the
# same args to regenerate.
#
# Output:
#   $OUTDIR/v{V}/{CLERS}.obj     — one OBJ per closed prime
#   $OUTDIR/no_close.txt         — CLERSes where puffup failed (one per line)
#   $OUTDIR/gen_summary.txt      — per-v counts and timing
#
# Requires:
#   src/puffup_c
#   ../clers/bin/clers
#   $PRIME_DIR/N.txt[.gz]   (default: ~/neo/data/primes)
#
# Env:
#   PRIME_DIR  prime CLERS source     (default: ~/neo/data/primes)
#   OUTDIR     OBJ store base         (default: ~/neo/data/objs)
#   JOBS       parallel jobs per v    (default: 80)

set -eu

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
PUFFUP="$ROOT/src/puffup_c"
DECODE="$(cd "$ROOT/../clers/bin" && pwd)/clers"
PRIME="${PRIME_DIR:-$HOME/neo/data/primes}"
OUTDIR="${OUTDIR:-$HOME/neo/data/objs}"
TMP="$ROOT/tmp_genobjs"
JOBS="${JOBS:-80}"

[ -x "$PUFFUP" ] || { echo "ERROR: $PUFFUP not found — run: make"; exit 1; }
[ -x "$DECODE" ] || { echo "ERROR: $DECODE not found (build clers first)"; exit 1; }
[ -d "$PRIME"  ] || { echo "ERROR: $PRIME not found (set PRIME_DIR)"; exit 1; }

V1="${1:-4}"
V2="${2:-50}"

mkdir -p "$OUTDIR" "$TMP"

SUMMARY="$OUTDIR/gen_summary.txt"
NOCLOSE="$OUTDIR/no_close.txt"

{
    echo "Generated by gen_objs_doob.sh on $(date)"
    echo "ideal commit: $(cd "$ROOT" && git rev-parse HEAD)"
    echo "primes data:  $PRIME/{v}.txt"
    echo
    printf '%-4s%12s%12s%12s%10s\n' v primes ok no_close secs
} > "$SUMMARY"

: > "$NOCLOSE"

worker() {
    local clers_file="$1"
    local objs_dest="$2"
    local work_dir="$3"

    mkdir -p "$work_dir/raw"
    "$DECODE" decode < "$clers_file" > "$work_dir/netcodes" 2>/dev/null
    "$PUFFUP" --obj-dir "$work_dir/raw" \
        < "$work_dir/netcodes" \
        > "$work_dir/puff.status" 2> "$work_dir/puff.err"

    # Rename {N}.obj → {CLERS_at_line_N}.obj. Print CLERSes that didn't
    # close (no OBJ produced) on stderr — collected into no_close.txt.
    awk 'NF > 0 { print NR, $0 }' "$clers_file" | while read -r n clers; do
        if [ -f "$work_dir/raw/${n}.obj" ]; then
            /bin/mv "$work_dir/raw/${n}.obj" "$objs_dest/${clers}.obj"
        else
            echo "$clers" >&2
        fi
    done

    /bin/rm -rf "$work_dir/raw"
}

export -f worker
export DECODE PUFFUP

for v in $(seq "$V1" "$V2"); do
    src=""; zc=""
    if   [ -f "$PRIME/${v}.txt.gz" ]; then src="$PRIME/${v}.txt.gz"; zc="zcat"
    elif [ -f "$PRIME/${v}.txt"    ]; then src="$PRIME/${v}.txt";    zc="cat"
    fi
    if [ -z "$src" ]; then
        printf '%-4d%12s%12s%12s%10s\n' "$v" "-" "-" "-" "-" >> "$SUMMARY"
        continue
    fi

    n=$($zc "$src" | grep -c '[A-Z]' || true)
    if [ "$n" -eq 0 ]; then
        printf '%-4d%12d%12d%12d%10d\n' "$v" 0 0 0 0 >> "$SUMMARY"
        continue
    fi

    dest="$OUTDIR/v${v}"
    mkdir -p "$dest"

    work="$TMP/v${v}"
    mkdir -p "$work"

    shards="$JOBS"
    [ "$n" -lt "$shards" ] && shards=$n

    /bin/rm -f "$work"/shard_*
    $zc "$src" | grep '[A-Z]' | split -n "l/$shards" - "$work/shard_"

    t0=$(date +%s)
    nice -n 19 parallel -j "$JOBS" \
        "worker {} '$dest' {}.work" \
        ::: "$work"/shard_* \
        2>> "$NOCLOSE" >/dev/null
    t1=$(date +%s)

    n_ok=$(ls "$dest" 2>/dev/null | wc -l | tr -d ' ')
    n_nc=$((n - n_ok))
    elapsed=$((t1 - t0))

    printf '%-4d%12d%12d%12d%10d\n' "$v" "$n" "$n_ok" "$n_nc" "$elapsed" >> "$SUMMARY"

    /bin/rm -rf "$work"
    echo "v=$v: $n primes, $n_ok ok, $n_nc no_close, ${elapsed}s" >&2
done

{
    echo
    echo "TOTAL v=${V1}..${V2}:"
    awk 'NR>5 && $2 != "-" { p+=$2; ok+=$3; nc+=$4; t+=$5 }
         END { printf "  %d primes  %d ok  %d no_close  %d secs\n", p, ok, nc, t }' \
        "$SUMMARY"
} >> "$SUMMARY"

rmdir "$TMP" 2>/dev/null || true
echo "wrote $OUTDIR/v{V}/{CLERS}.obj, $SUMMARY, $NOCLOSE"
