#!/bin/bash
# run_closure_doob.sh [V1 [V2]]
#
# Run puffup_c against every prime 6-net at vertex counts V1..V2
# (default 4..50) and emit a closure summary.
#
# Output: data/v${V1}_${V2}_closure.txt
#   v       primes      ok          retries
#   4         1           1    0
#   ...
#   TOTAL across v=V1..V2:
#     <total> primes
#     <total> ok
#     <retries> needed retry
#
# Requires:
#   src/puffup_c compiled (run: make)
#   ../clers/bin/clers   (the CLERS decoder C binary)
#   $PRIME_DIR/N.txt[.gz]  (default: ~/neo/data/primes)

set -e

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
PUFFUP="$ROOT/src/puffup_c"
DECODE="$(cd "$ROOT/../clers/bin" && pwd)/clers"
PRIME="${PRIME_DIR:-$HOME/neo/data/primes}"
TMP="$ROOT/tmp_closure"
JOBS=80

[ -x "$PUFFUP" ] || { echo "ERROR: $PUFFUP not found — run: make"; exit 1; }
[ -x "$DECODE" ] || { echo "ERROR: $DECODE not found (build clers first)"; exit 1; }
[ -d "$PRIME"  ] || { echo "ERROR: $PRIME not found (set PRIME_DIR)"; exit 1; }

V1="${1:-4}"
V2="${2:-50}"
OUT="$ROOT/data/v${V1}_${V2}_closure.txt"

mkdir -p "$TMP" "$ROOT/data"

{
    echo "Generated by puffup_c on $(date)"
    echo "ideal commit: $(cd "$ROOT" && git rev-parse HEAD)"
    echo "primes data:  $PRIME/{v}.txt"
    echo
    printf '%-8s%-12s%-12s%s\n' v primes ok retries
} > "$OUT"

total_p=0; total_ok=0; total_re=0

for v in $(seq "$V1" "$V2"); do
    src=""; zcat=""
    if   [ -f "$PRIME/${v}.txt.gz" ]; then src="$PRIME/${v}.txt.gz"; zcat="zcat"
    elif [ -f "$PRIME/${v}.txt"    ]; then src="$PRIME/${v}.txt";    zcat="cat"
    fi

    if [ -z "$src" ]; then
        printf '%2d  %10s  %10s %4s\n' "$v" "-" "-" "-" >> "$OUT"
        continue
    fi

    nlines=$($zcat "$src" | grep -c '[A-Z]' || true)
    if [ "$nlines" -eq 0 ]; then
        printf '%2d%12d%12d%5d\n' "$v" 0 0 0 >> "$OUT"
        continue
    fi

    shards=$JOBS
    [ "$nlines" -lt "$shards" ] && shards=$nlines

    rm -f "$TMP"/cl_${v}_*
    $zcat "$src" | grep '[A-Z]' | "$DECODE" decode | split -n "l/$shards" - "$TMP/cl_${v}_"

    nice -n 19 parallel -j "$JOBS" \
        "$PUFFUP < {} > {}.out 2>/dev/null" \
        ::: "$TMP"/cl_${v}_*

    n_ok=$(awk '$1=="ok"'        "$TMP"/cl_${v}_*.out | wc -l | tr -d ' ')
    n_re=$(awk '$1=="ok" && $7==1' "$TMP"/cl_${v}_*.out | wc -l | tr -d ' ')

    printf '%2d%12d%12d%5d\n' "$v" "$nlines" "$n_ok" "$n_re" >> "$OUT"

    total_p=$((total_p + nlines))
    total_ok=$((total_ok + n_ok))
    total_re=$((total_re + n_re))

    rm -f "$TMP"/cl_${v}_* "$TMP"/cl_${v}_*.out
done

{
    echo
    echo "TOTAL across v=${V1}..${V2}:"
    printf '  %d primes\n'        "$total_p"
    printf '  %d ok\n'            "$total_ok"
    printf '  %d needed retry\n'  "$total_re"
} >> "$OUT"

rmdir "$TMP" 2>/dev/null || true
echo "wrote $OUT"
